id,title,author,isbn,rate,img,review
2,They All Saw a Cat,Brendan Wenzel,1452150133,4.75,https://ia800505.us.archive.org/view_archive.php?archive=/25/items/m_covers_0010/m_covers_0010_54.zip&file=0010540120-M.jpg,"It’s funny. Unless you’re a teacher or librarian, a grown adult that does not work or live with children will come into very little contact with picture books. Then, one day, they produce a few kids and BLAMMO! They are shot into a world they haven’t visited since they were young themselves. They grab frantically at the classics, discover that a lot of them don’t work with very very young children (since when did Horton Hatches the Egg have so many words?!?), and then occasionally turn to the experts for help. And why? Parents’ reasons are not united on this front. Some read to their kids to instill a love of reading. Others to build little brains. Others to simply fill the long hours of the day. Occasionally a parent will also use a book to teach some kind of a lesson. If the parent is unlucky they will get stuck with a book sticky with didacticism (an unpleasant book that sucks all the joy out of the reading experience). But if they are lucky (or they are in the hands of a capable professional) they might find just the right book, teaching just the right lesson. Here’s an example: Let’s say you wanted to teach a kid empathy or how our perceptions change depending on our own experiences and who we are. How do you show that in 32 pages? Well, you could pick up some cloying, toxic dribble that overuses words like “hugs” and “friendship”. Nine times out of ten, that’s what’s going to happen. Or, if you are a clever parent, you pick up a book like They All Saw a Cat. It looks at first glance like it’s just about a cat. Delve a little deeper and you’ll find it about science and art and perception and empathy. And it does it all with very simple sentences, repetition, and a lot of white backgrounds. Not too shabby. Not too shabby at all.

“The cat walked through the world, with its whiskers, ears, and paws . . .” In that walking it is seen. It is seen by a child, a dog, and a fox. It is seen by a fish, a mouse, and a bee. It is seen by a bird, a flea, a snake, a skunk, a worm, and a bat. And what is important is that this “seeing” changes with every creature. For mice and dogs, the cat is perceived through the lens of their own interactions with it. For worms and bats the cat is only visible through the ways in which it moves through space (vibrations through the ground and the ways in which echolocation shape it). By the end we see a hodgepodge cat, a mix of how each animal sees it. Then the cat comes to the water, viewing its own reflection, “and imagine what it saw?”

The book this actually reminded me of the most was that old Rudyard Kipling story “The Cat Who Walked By Himself”. Unlike that tale we never really get this book from the cat’s perspective. Indeed, the cat is often only visible when others see him. The similarity to Kipling comes with the language. That very first sentence, for example: “The cat walked through the world, with its whiskers, ears, and paws . . .” And as in the original art for that story, the cat here is often pictured from the back. There’s a lot of debate about whether or not a book written by one person and illustrated by another can ever be as strong as a book that is written and illustrated by the same artist. They All Saw a Cat makes a fairly strong argument that artist who are also authors are the better way to go. Wenzel’s sentences are so perfectly layered here. If anything, they match the personality of a cat. There aren’t many words, true. But the measured tone is at once soothing and scintillating. I liked how the book broke up the animals. The first three are potential predators. The second three are potential prey. The final six are strict observers. It also ends perfectly with the best possible sentence. Not all picture books, no matter how beautiful they look, are capable of sticking their landings. This one does.

In this book the publication page (where they tend to describe the artist’s process) gets a little slaphappy. It reads (and I am quoting this precisely), “The illustrations in this book were rendered in almost everything imaginable, including colored pencil, oil pastels, acrylic paint, watercolor, charcoal, Magic Marker, good old number 2 pencils, and even an iBook.” The other day I was listening to a podcast where one of the speakers speculated that including this kind of information in a book changes the adult reader’s perspective. Would I think less of this book if I found out it was done in digital ink? Possibly, though I should note that I was blown away by the art long before I ever turned to see how it was made. And while digital art is great and has its place, I’d like to see the program that replicates what Wenzel’s done here.

The sheer beauty of the book is what strikes you first when you read it. Consider the two-page spread where on the left-hand side you see the cat through snake vision, and on the right-hand side you see the cat through skunk vision. The snake’s view is a vibrant shock of color, all yellows and reds and blues. The skunk’s in contrast, looks like the soft grainy sepia-tones of an old film. Maybe Casablanca. Put together, side-by-side, the same cat is its own opposite. But if Wenzel were constantly wowing you with eye-popping images that wouldn’t really support the narrative flow. That’s why the pacing of the book is key. Wenzel starts the book out very slowly, with lots of white backgrounds and views akin to what we see as people. The child, dog, and fox all see the cat similarly (though I loved the oversized bell around its neck, indicating the fox and dog’s superior sense of hearing through a visual medium). The fish is the first moment you start to separate from human visuals. The cat’s large, yellow eyes are 80% of the two pages. But it is the mouse’s Basquiat-esque view of the cat that steals the show. The red background, and the cat all teeth and claws, and terrifying eyes is a far cry from the cuddly creature at the start of the story. It’s also the moment when the child readers come to realize that perception is personal.

An interesting criticism of this book is linked precisely to the more science-y aspects of the text. One of the commenters on a blog post I wrote, that included this book, said that, “I desperately wanted some nice science-y back matter to tell us how and why different animals see the cat the way they do. Sure, we can go OH, this animal must be colorblind! This animal ‘sees’ by sonar! But c’mon, throw us an edu-bone here. It felt like such a missed opportunity.” This is an interesting note. We’ve grown used to useful backmatter in this post-Core Curriculum world of ours. Would this book have been stronger if it had contained a science element to it? Yes and no. It would have been a real boon to teachers, you betcha, and probably to perceptive parents who could have turned it into a lesson for young readers. If I had to guess I’d say the reason it wasn’t done may have had something to do with the fact that Wenzel is mixing his fact and fiction here pretty closely. Each animal is “seeing” as it would in the wild, but that is not to say that the art is by any means scientific. The cartoonish quality to the animals (no better exemplified than in the mouse’s bulbous eyes) doesn’t hold up to close scrutiny. I would have very much liked notes on the accuracy of the art, but I can understand the fear of asking the reader to take the work too seriously. I don’t necessarily agree, but I understand it.

How do you discuss this book with kids? Well, you might read it to them, start to finish, and then ask them which picture shows what the cat really looks like. When they select (some will go with the human view but I’ve no doubt a couple will prefer the dog or bird p.o.v.s) you then tell them that actually all the pictures in this book are true. And if you really want to blow their little minds, you tell them that there’s a good chance that the way you see the world isn’t the same way the person next to you does. Everyone, everywhere sees the world different from his or her neighbor. Is it any wonder we have problems? The solution is to try and see things from another person’s view. Now, if the kids think you’re speaking literally or figuratively, it doesn’t really matter. You’ve planted the seed. Or, rather, the book has.

Let us do away with the notion of “cat people” vs. “dog people”. This book is for “people”. End of sentence. And if I got a little crazy in my first paragraph here, filling you in on my view of world peace via picture books, you’ll understand when you read this book. That tired old phrase to “walk a mile in someone else’s shoes” makes no sense to a kid. But travel a page through another animal’s eyes? There’s never been a better fictional picture book that allows you to do this. If we all see something as simple as a cat this differently, what else might we not see the same? It’s a treat to eye, ear, and mind, but don’t forget. We’re all going to see this book through our own lenses. What will your kids see when they look at it? Only one way to find out."
3,The Girl with the Dragon Tattoo,Stieg Larsson,670069019,4.05,https://ia600505.us.archive.org/view_archive.php?archive=/10/items/m_covers_0011/m_covers_0011_00.zip&file=0011005892-M.jpg,"After having leaped onto the bandwagon with the rest of everyone, I feel a certain amount of pretentious indie pride saying that I was not as awed by this book as everyone else apparently was. Which is not to say that the book was not enjoyable and exciting; it just did not knock my socks off whilst simultaneously blowing my mind and rocking my world. (that sounds like either some great song lyrics or a very complicated sexual maneuver. Let us go with the first option.)

So, the good stuff: the main story - a disgraced journalist is hired by a rich old man to write a book about said man is crazy rich family, while secretly working to discover truth behind the disappearance and supposed murder of the man is granddaughter. Also in play is Lisbeth Salander, a freelance investigator who also happens to be one of the best hackers in Sweden. She also happens to be made of awesome, but I will get to that later.
The journalist is investigating a supposed murder (a body was never found, so no one even knows what happened to the girl), so violence is expected. I just was not quite prepared for just how intensely graphic the violence is. There is a lot of stuff dealing with assault, rape, and murder of various women. There is also a lot of sex in the book, and the stuff that gets described in the most detail is definitely not consensual and will probably make you very uncomfortable. You have been warned.
The investigation itself is pretty fascinating, implausible as it is that some random guy investigating a disappearance that took place 40 years ago was able to find out completely new leads that were not found by the police or the girl is grandfather (who is been obsessing about the case since forever), but I digress. The family itself is equal parts interesting, creepy, and frustrating. It is not until the journalist (Blomkvist) teams up with Lisbeth that things get really interesting, and they made such a fun team I wanted them to get their own detective show.
The book deals mainly with crimes against women and those who commit them. Larsson obviously feels very passionately about this subject, as well as what should be done with the men who assault women. Without giving anything away, rest assured that every bad guy rapist/murderer/whatever gets a large helping of tasty justice.

And now for the bad stuff:
-There is a lot of nattering on about business and computers and journalism and more business stuff that either bored me or went over my head completely.
-Larsson cannot seem to decide whether he wants to refer to people by their last name or their first name, so he switches back and forth and it is confusing.
-A family tree is provided at the beginning of the book, since the family the journalist is investigating (the Vangers) is pretty big, but I never had much trouble keeping everyone straight. A map of the island the family compound is located on would have been much more helpful, since I never really figured out the geography of the place.
-Pointless details. I do not need to know what the characters ate for every single meal, I don not need to know exactly what model of computer/motorcycle/car a character uses, and I definitely do not need to know what each character is wearing at every moment of the day. Larsson is especially guilty of this when Lisbeth is concerned - I guess he decided we would not understand what a unique counterculture tough chick she is unless we know that she is always wearing leather jackets, boots, torn jeans, and black t-shirts with angry slogans. (yes, Larsson actually tells us what each of Lisbeth is t-shirts says.) Listen, Stieg: Lisbeth is awesome. She is wonderfully defined simply through her own actions and thoughts - we don not even need the other characters constantly reminding us how antisocial and tough and uncommunicative and badass she is. Believe me, we can see that. Show don not tell etc.

To sum up, I am going to give the last word to the book itself, and quote a sentence that is actually a character talking about a book featured towards the end of the story - but it could easily describe Larsson is book:
'"It was uneven stylistically, and in places the writing was actually rather poor - there had been no time for any fine polishing - but the book was animated by a fury that no reader could help but notice.'"

That, in a nutshell, was how I felt about The Girl With the Dragon Tattoo."
4,A Game of Thrones,George R. R. Martin,553381687,4.42,https://ia800505.us.archive.org/view_archive.php?archive=/10/items/m_covers_0011/m_covers_0011_29.zip&file=0011291394-M.jpg,"I have finally done it! I have joined in on the fun that is A Game of Thrones. It is 2018 and I managed to make it all the way here without reading a page or watching a minute of the show. Now, it is the nature of the internet to keep me from being completely in the dark on this one, but I think I did a pretty good job of avoiding hearing or seeing too much about it.

Is this a great fantasy book? It really is quite good. The plot and the characters are well thought out. Comparing it to other fantasy books I have read, it is right up there or better.

Yeah, but since this has been taking the world by storm it must have blown your socks off!? Um, no, not really. It was good, but not, '"OMG THIS IS THE BEST THING EVER!'" good.

How about mainstream interest? So many people say they are not fantasy fans but they love this series. This has to be 95% because of the show. This book is SOOOOOOO fantasy, if it wasn''t already popular I would never recommend it to anyone except a diehard fantasy fan. In fact, it isn''t even really '"fun'" fantasy - it is dark with lots of politics and plotting. Some of my Goodreads friends said that historical fiction fans get a kick out of it, too, and it is loosely based on the War of the Roses.

Do I want to watch the show now? Yeah, I think I will check it out.

Sex and violence? I have seen some people wary of this book because of sex and violence. Internet spoilers, SNL skits, etc. sure do make it sound pretty vicious and risque. However, compared to other fantasy novels, it is pretty normal. In fact, the depiction of sex is pretty tame. Violence is maybe a little more intense, but nothing that made me feel the book was too extremely brutal. Perhaps these things get amped up in future books?

EVERONE DIES! One thing that seemed to leak through the internet and my friends talking about the book was to not get too attached to a character because they will probably die. So far, only one death was kind of shocking to me. I expect the death count and the shock value to go up as the books progress.

I think that covers the main points.
- I liked it, but wasn''t completely blown away.
- I have no idea how HBO managed to get a bunch of non-fantasy fans into this.
- I cannot wait to check out the next one to see what happens!"
5,Anthem,Ayn Rand & Erin Bateman,525940154,3.38,https://covers.openlibrary.org/b/id/802982-M.jpg?default=%27https://openlibrary.org/images/icons/avatar_book.png%27,"he book is about human identity and freedom, and how one can degrade under the chains of collectivism.

A lot of reviews on this book, which are posted on this site, use the word “futuristic” events. I intentionally put the quotes around this word as I tend to totally disagree with the choice of this word. I used to live under socialist regime, a collectivistic society. So I can relate and completely understand the events described in the book, where the word “I” doesn’t exist, when it is a shame to stand out and be different from the rest.
However, you don’t need to come from the socialist country to understand that this is about NOW, and not the future. We face this “phenomenon” (again I am using the quotes to underline that this actually is a normal event that we face every day), when we need to struggle to form our own opinions to think this is white, when everyone else thinks this is black. We struggle to stand up and not to get under the influence of the media propaganda and continue to act with the high integrity and high morals no matter what.

This book is about the man, who stands out on his own and is not afraid to position himself against everyone else just to rediscover his “I”.

My favorite quotes:

'"My hands...My spirit...My sky...My forest'".

'"I wished to know the meaning of things. I am the meaning'"
Many words have been granted me,...but only three are holy: '"I will it!'"

'"I am a man. This miracle of me is mine to own and keep, and mine to guard, and mine to use, and mine to kneel before.'"

“ I am neither foe nor friend to my brothers, but such as each of them shall deserve of me. And to earn my love, my brothers must do more than to have been born. I do not grant my love without reason, nor to any chance passer-by who may wish to claim it. I honor men with my love. But honor is a thing to be earned.'"

And now I see the face of god... . This god, this one word: ''I''

'"...man will go on. Man, not men.'"

'"I am. I think. I will.'""
6,The Hunger Games,Suzanne Collins,439023483,4.08,https://covers.openlibrary.org/b/id/14552116-M.jpg,"In a post-apocalyptic future, life has turned extremely hard. Fighting poverty and hunger every day, sixteen years old hunter Katniss does absolutely everything in her power to have enough for her defenseless little sister, and a barely lucid mother. Life is hard, yet not impossible, until the one fateful day arrives. Once every year, the ever vigilant all powerful Capitol of Panem celebrates for their entertainment the “Hunger Games”, a yearly tournament where a handful representatives of each district are forced to fight in a massive arena, to the death. In a sad turn of events, young Katniss will have to fight not only for herself, but for the future of her starving family.

I think this series needs as much introduction as Lord of the Rings; but what the hey, old habits die hard. Maybe not everyone has read it, maybe not everyone has watched it, but doubt anyone has never heard of it at some point. One of the greatest dystopian fiction of all time, or at least one of the best-selling ones. A literature masterpiece? Hardly. One of the most entertaining ever? Quite possibly! Astounding world building and character development. Not a profound reading at all, but a plot perfectly balanced, fast paced and action packed; if you can withstand YA that is, and the triangle thingy. Along with Percy Jackson and Divergent, one of the pillar series that sparked my literary addiction. Highly Recommendable.

*** Hunger Games (2012) is a superb adaptation, maybe as good as the book, if not better. Highly popcorn and re-watch worthy. I don’t normally reread, or feel the desire to; but lost count of how many times I’ve watched the movie on TV. It just never gets old, and is perfect, for what it is; really bringing the characters alive in a way a book never can, and few adaptations ever succeed. Jennifer Lawrence and Josh Hutcherson just marvelous in their roles, with an unforgettably heartbreaking performance by Amandla Stenberg as Rue too. Still, even a decade later I can never forget that Madge Undersee was left out of the adaptation; and the Tessera system hardly explained or mentioned; along with a few other minor things cut out. Not one of the greatest films but one of the greatest adaptations ever, hands down. One of those few cases where I think I ultimately prefer the movie rather than the book. Extremely Recommendable."
